### ISSUE TITLE
Moving project to another maintained repository

### ISSUE THREAD

**Issue by Demmonius** [Jimdo/serverless-dotenv#8]
Hi everyone,

As you saw in PR section, this package is no longer maintained so we forked the repository there: 
https://github.com/UnlyEd/serverless-env-copy-plugin

We have made changes, such as renaming the plugin (was confusing) and fixed some of the open PR reported [here](https://github.com/Jimdo/serverless-dotenv/pulls).

We are open for changes and pull requests, don't hesitate to share your thoughts there. 
Let's bring this plugin to life and improve it !

**Comment by Lusitaniae** [comment]
@Demmonius Would be nice if Issues were enabled

**Comment by Vadorequest** [comment]
@Lusitaniae Issues and discussions were enabled just now!
